on:
  # push:
  #   branches: [main, master]
  # pull_request:
  #   branches: [main, master]
  workflow_dispatch:
  schedule:
    - cron: '31 6 * * TUE' # run on Tuesdays at 6:31 UTC

name: Check-install-win-11-arm

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: windows-11-arm

    name: windows-11-arm

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Install R aarch64
        run: |
          $ErrorActionPreference = 'Stop'
          $url = "https://github.com/remlapmot/r-build-for-windows-on-gha/releases/download/R-4.6.0/R-4.6.0-aarch64-openblas.exe"
          Invoke-WebRequest -Uri "$url" -OutFile R-aarch64.exe -UseBasicParsing -UserAgent "NativeHost"
          Start-Process -FilePath R-aarch64.exe -ArgumentList "/install /norestart /verysilent /SUPPRESSMSGBOXES" -NoNewWindow -Wait
          "C:\Program Files\R-aarch64\R-4.6.0\bin" >> $env:GITHUB_PATH

      - name: Install Rtools45
        run: |
          $ErrorActionPreference = 'Stop'
          $url = "https://cran.r-project.org/bin/windows/Rtools/rtools45/files/rtools45-aarch64-6768-6492.exe"
          Invoke-WebRequest -Uri "$url" -OutFile rtools45-aarch64.exe -UseBasicParsing -UserAgent "NativeHost"
          Start-Process -FilePath rtools45-aarch64.exe -ArgumentList "/install /norestart /verysilent /SUPPRESSMSGBOXES" -NoNewWindow -Wait
          "C:\rtools45-aarch64\usr\bin" >> $env:GITHUB_PATH

      - name: Install pandoc
        run: choco install pandoc --no-progress

      - name: Install TwoSampleMR and report session info
        run: |
          $ErrorActionPreference = 'Stop'
          Rscript -e "print(R.version); install.packages('TwoSampleMR', dependencies = TRUE, repos = c('https://cloud.r-project.org/', 'https://mrcieu.r-universe.dev')); library(TwoSampleMR); install.packages('sessioninfo', repos = 'https://cloud.r-project.org/'); sessioninfo::session_info(pkgs = 'installed')"

      - name: Install TinyTeX
        run: |
          $ErrorActionPreference = 'Stop'
          Rscript -e "install.packages(c('tinytex'), repos = 'https://cloud.r-project.org/'); tinytex::install_tinytex(); tinytex::tlmgr_install(c('makeindex', 'upquote', 'inconsolata'))"
          "C:\Users\runneradmin\AppData\Roaming\TinyTeX\bin\windows" >> $env:GITHUB_PATH

      - name: Clone TwoSampleMR and remove installed version
        run: |
          $ErrorActionPreference = 'Stop'
          git clone --depth 1 https://github.com/MRCIEU/TwoSampleMR.git
          Rscript -e "remove.packages('TwoSampleMR')"

      - name: R CMD check
        run: |
          $ErrorActionPreference = 'Stop'
          Rcmd build TwoSampleMR
          $tarball = Get-ChildItem -Filter "TwoSampleMR_*.tar.gz" | Select-Object -First 1 -ExpandProperty Name
          Rcmd check --as-cran $tarball
